version: "3.4"

networks:
  automation-cluster:
    external:
      name: automation-cluster

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: automation_proxy
    networks:
      - automation-cluster
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/ssl/prettybaked_wildcard
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mqtt:
    container_name: automation_mqtt
    image: eclipse-mosquitto:latest
    networks:
      - automation-cluster
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /etc/localtime:/etc/localtime:ro

  master:
    container_name: automation_master
    image: homeassistant/home-assistant:0.95.4
    networks:
      - automation-cluster
    ports:
      - 8123:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configs/master:/config
    environment:
      - VIRTUAL_HOST=master.automation.home.prettybaked.com
      - VIRTUAL_PORT=8123
    depends_on:
      - mqtt
  
  settings:
    container_name: automation_settings
    image: homeassistant/home-assistant:0.100.3
    networks:
      - automation-cluster
    ports:
      - 8001:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configs/settings:/config
    environment:
      - VIRTUAL_HOST=settings.automation.home.prettybaked.com
    depends_on:
      - mqtt
      - master

  appliances:
    container_name: automation_appliances
    image: homeassistant/home-assistant:0.100.3
    networks:
      - automation-cluster
    ports:
      - 9000:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configs/appliances:/config
    environment:
      - VIRTUAL_HOST=appliances.automation.home.prettybaked.com
    depends_on:
      - mqtt
      - master

  communication:
    container_name: automation_communication
    image: homeassistant/home-assistant:0.100.3
    networks:
      - automation-cluster
    ports:
      - 9001:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configs/appliances:/config
    environment:
      - VIRTUAL_HOST=communication.automation.home.prettybaked.com
    depends_on:
      - mqtt
      - master

  environment:
    container_name: automation_environment
    image: homeassistant/home-assistant:0.100.3
    networks:
      - automation-cluster
    ports:
      - 9002:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configs/environment:/config
    environment:
      - VIRTUAL_HOST=environment.automation.home.prettybaked.com
    depends_on:
      - mqtt
      - master

  hubs:
    container_name: automation_hubs
    image: homeassistant/home-assistant:0.95.4
    networks:
      - automation-cluster
    ports:
      - 9003:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configs/hubs:/config
    environment:
      - VIRTUAL_HOST=hubs.automation.home.prettybaked.com
    depends_on:
      - mqtt
      - master

  media:
    container_name: automation_media
    image: homeassistant/home-assistant:0.100.3
    networks:
      - automation-cluster
    ports:
      - 9004:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configs/media:/config
    environment:
      - VIRTUAL_HOST=media.automation.home.prettybaked.com
    depends_on:
      - mqtt
      - master

  planning:
    container_name: automation_planning
    image: homeassistant/home-assistant:0.100.3
    networks:
      - automation-cluster
    ports:
      - 9005:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configs/planning:/config
    environment:
      - VIRTUAL_HOST=.automation.home.prettybaked.com
    depends_on:
      - mqtt
      - master

  security:
    container_name: automation_security
    image: homeassistant/home-assistant:0.101.3
    networks:
      - automation-cluster
    ports:
      - 9006:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configs/security:/config
    environment:
      - VIRTUAL_HOST=security.automation.home.prettybaked.com
    depends_on:
      - mqtt
      - master

  trackers:
    container_name: automation_trackers
    image: homeassistant/home-assistant:0.100.3
    networks:
      - automation-cluster
    ports:
      - 9007:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configs/trackers:/config
    environment:
      - VIRTUAL_HOST=trackers.automation.home.prettybaked.com
    depends_on:
      - mqtt
      - master
