version: "3.4"

networks:
  automation-cluster:
    external:
      name: automation-cluster

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: automation_proxy
    restart: always
    networks:
      - automation-cluster
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mqtt:
    container_name: automation_mqtt
    image: eclipse-mosquitto:latest
    restart: always
    networks:
      - automation-cluster
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - nginx-proxy

