version: "3.4"

networks:
  automation-cluster:
    external:
      name: automation-cluster

services:
  doods:
    image: snowzach/doods:latest
    container_name: automation_obj_detection
    restart: always
    networks:
      - automation-cluster
    ports:
      - 10001:8080
    volumes:
      - ./services/doods/models:/opt/doods/models
      - ./services/doods/detector.yaml:/opt/doods/config.yaml
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/apex_0:/apex_0
    privileged: true

