version: "3.4"

networks:
  automation-cluster:
    external:
      name: automation-cluster

services:
  rules:
    container_name: automation_rules
    image: acockburn/appdaemon:4.0.1
    restart: always
    networks:
      - automation-cluster
    ports:
      - 5050:5050
    volumes:
      - ./configs/rules:/conf
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - VIRTUAL_HOST=rules.automation.home.prettybaked.com
      - VIRTUAL_PORT=443